# Generated by Django 4.2.13 on 2024-07-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('gender', models.CharField(max_length=1)),
                ('activity', models.FloatField()),
                ('goal', models.FloatField()),
                ('BMI', models.FloatField()),
                ('BMR', models.FloatField()),
                ('ProteinIntake', models.FloatField()),
                ('CarbsIntake', models.FloatField()),
                ('FatIntake', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
