# Generated by Django 4.2.13 on 2024-07-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='CaloriesIntake',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
